services:

  webapp:
    build: .
    ports:
      - "8080:80"

  mariadb:
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: logsdb
      MARIADB_USER: logsuser
      MARIADB_PASSWORD: logspass
    volumes:
      - ./db/db_init.sql:/docker-entrypoint-initdb.d/db_init.sql:ro
      - db_data:/var/lib/mysql

volumes:
  db_data:
