services:

  webapp:
    build: .
    ports:
      - "8080:80"

  mariadb:
    image: mariadb:11
    volumes:
      - ./db/db_init.sql:/docker-entrypoint-initdb.d/db_init.sql:ro
      - db_data:/var/lib/mysql

volumes:
  db_data:
